name: MrFafo Frontend - Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  # test:
  #   runs-on: ubuntu-latest
    
  #   permissions:
  #     # Required to checkout the code
  #     contents: read
  #     # Required to put a comment into the pull-request
  #     pull-requests: write

  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: 'Install Node'
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: '17'

  #   - name: 'Install Deps'
  #     run: |
  #       npm install
  #       npm run build

  #   - name: 'Test'
  #     run: npx vitest --coverage

  #   - name: 'Report Coverage'
  #     if: always() # Also generate the report if tests are failing
  #     uses:  davelosert/vitest-coverage-report-action@v2

  build-push:
    # needs: test
    env:
      REGISTRY: ghcr.io/devozs
      IMAGE: mrfafo-frontend
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: Generate build ID
        id: prep
        run: |
            branch=${GITHUB_REF##*/}
            sha=${GITHUB_SHA::8}
            ts=$(date +%s)
            echo "BUILD_ID=${branch}-${sha}-${ts}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: "Build"
        run: |
          docker build -f Dockerfile . -t ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Docker Push"
        run: |
          docker tag ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }} ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
